name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.3
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    - name: Build, test, and code coverage
      run: make
   - name: Create Coverage Badge
     uses: schneegans/dynamic-badges-action@v1.7.0
     with:
       auth: ${{ secrets.GIST_UPDATE }}
       gistID: 8a47cae880f266d624470c768706af2c
       filename: auv3-support--coverage.json
       label: Coverage
       message: ${{ env.PERCENTAGE }}
       color: success
